### ISSUE TITLE
Why was patternGroups deprecated?

### ISSUE THREAD

**Issue by Venryx** [epoberezkin/ajv-keywords#15]
The readme lists the "patternsGroups" keyword as deprecated.

It seems like there are some cases where it could be useful -- so I'm curious, why was it removed?

Is it because the good majority of use-cases can also be accomplished with "patternProperties" + "additionalProperties: false", and so keeping it is kind of redundant/not worth the maintenance effort?

(P.S. Great library, by the way. I especially like the ability to add custom keywords, as it lets you integrate pretty much all (if not all) validation logic into the schema system.)

**Comment by epoberezkin** [comment]
The reasons to deprecate:
1. It cannot be easily separated from Ajv (it can only be implemented as part of properties keyword because it changes additionalProperties).
2. It is highly unlikely it ever becomes part of the standard, if any extension is added it will be more generic than patternGroups, allowing matching to arbitrary schemas too (like propertyNames does), not just to patterns.
3. The use case for it is quite narrow and usually follows from bad data design.
4. The only useful thing is to ensure that some pattern is present is covered by patternRequired and if you want more than one property in cases you don't mix multiple patterns you can use minProperties.
