### ISSUE TITLE
keyword select requires $data option

### ISSUE THREAD

**Issue by retorquere** [epoberezkin/ajv-keywords#17]
When I try the example from the README:

```
var Ajv = require('ajv');
var ajv = new Ajv;
require('ajv-keywords')(ajv);

ajv.validate({ instanceof: 'RegExp' }, /.*/); // true
ajv.validate({ instanceof: 'RegExp' }, '.*'); // false
```

I get `keyword select requires $data option`.

It still seems to work, but I don't know what to make of the warning.

**Comment by epoberezkin** [comment]
You can add only the keywords you use rather than all: https://github.com/epoberezkin/ajv-keywords#usage

**Comment by retorquere** [comment]
I've done that, but still, the README as-is emits a warning when executed.

**Comment by epoberezkin** [comment]
Can be changed I guess... This usage that adds all keywords can be the third option so the code sample adds just one keyword. There won't be warning if you use $data option, as it suggests.

**Comment by smeijer** [comment]
> Also, there won't be warning if you use $data option, as it suggests

Those last words will fix the warning indeed. When enabling `select` from this package, you should also specify that `$data` must be enabled.

The warning made me look at the `select` property of my schema. I thought that something was wrong with my `select: { $data: '0/...' }` attribute, but it turned out that the usage of `$data` is disabled by default.

So, this is how you don't throw the warning:

```js
import Ajv from 'ajv';
import extendAjv from 'ajv-keywords';

const ajv = new Ajv({ $data: true });
extendAjv(ajv);
```

**Comment by epoberezkin** [comment]
That is correct :)
