### ISSUE TITLE
Typeof bigint

### ISSUE THREAD

**Issue by zdm** [epoberezkin/ajv-keywords#251]
Could you please add `bigint` to the `typeof` keyword?

**Comment by epoberezkin** [comment]
I think it would require adding bigint support to ajv... It could potentially be limited just to this keyword, if you make the PR we can assess if it is ok as an isolated change.

**Comment by zdm** [comment]
Why?
`typeof` just checks types, without coercions or other things.
I think it will be enough to add `bigint` here:
```
const TYPES = ["undefined", "string", "number", "object", "function", "boolean", "symbol"]
```

**Comment by epoberezkin** [comment]
> Why?

well, because none of the keywords you expect to work with integer would work with bigint... Also, it seems to have a limited utility as JSON.parse cannot be configured to parse as bigint.

But I don't mind adding it to typeof here only, with the disclaimer in the docs that none of the other keywords that apply to numbers/integers apply to bigint...

**Comment by zdm** [comment]
I will come back to this issue a bit later.

**Comment by zdm** [comment]
Noy actually needed. we decided to not use biginy at all
