### ISSUE TITLE
Keyword discriminator from Open API 3 Specification

### ISSUE THREAD

**Issue by epoberezkin** [epoberezkin/ajv-keywords#35]

**Comment by epoberezkin** [comment]
No. This keyword is for tools only in v3, it doesn't do any validation any more.

**Comment by oeN** [comment]
Sorry to bother you again. 
Is there a way to have a valid swagger schema, that can be validated with Ajv, that results with the same behavior of `oneOf` and the `discriminator` keyword?

**Comment by epoberezkin** [comment]
I may be wrong, but I think in OpenAPI v3 you must use oneOf, discriminator is just to inform the tools what is the logic behind these oneOfs. My understanding is that removing discriminator in v3 should always result in the same validation outcome (valid/invalid), but may affect error reporting or some other behaviours. So from validation point of view it can be just ignored.

**Comment by oeN** [comment]
👍 thank you! I've studied a little and in the end, I've used the `if/then/else` and replaced the pre-commit test from `swagger-cli api:test ..` to `ajv compile ...`

**Comment by cdimascio** [comment]
@epoberezkin for the most part, this [statement](https://github.com/epoberezkin/ajv-keywords/issues/35#issuecomment-444144385) is accurate, however, i believe when defaults are involved the discriminator is necessary to clear up ambiguities. 

For example, given this [openapi 3 spec](https://raw.githubusercontent.com/cdimascio/express-openapi-validator/5c40cce56707857c4f6d81b2693b1f33fb70b890/test/resources/one.of.discriminator.yaml) where `TypeOne` and `TypeTwo` are `oneOf` and have a property, `value`, that has a different default depending on the the discriiminator, `type`. Without taking into consideration the discriminator, the wrong default can be used.

Is there a way this can be solved?

**Comment by catadch** [comment]
@cdimascio raised this issue in response to one I raised with him against the otherwise excellent [express-openapi-validator](https://www.npmjs.com/package/express-openapi-validator) I'm using in a high profile project. 

The schema is enormous and was intented to include many thousands of constant values. However, as [discussed](https://github.com/OAI/OpenAPI-Specification/issues/1313) for over two years now, OpenAPI 3.x does not support a constant datatype, though JSON Schema does. 

Our client demands the API be specified in OpenAPI 3 so I was using the _"enum with one value and default"_ work-around in lieu of a constant type, but this broke @cdimascio's validator, and every other one I tried, when combined with discriminators for oneOf.

I do not have the luxury of waiting for a fix, but would like to know the OpenAPI community is considering this as an enhancement to the specification so my manual, ugly hack to provide consumers with easy access to thousands of identically named but differently scoped constant values can eventually be consigned to the bin.

**Comment by epoberezkin** [comment]
created see https://github.com/epoberezkin/ajv/issues/1119 for discriminator keyword

discrimitator cannot be implemented as a separate keyword, only as an extension of oneOf functionality - from validation point of view it's no-op.

Defaults are just meta-data from JSON Schema spec point of view, the spec does notdefine how it should be processed.
